apiVersion: v1
kind: PersistentVolume
metadata:
  name: changedetection-storage-pv
spec:
  capacity:
    storage: 5Gi
  volumeMode: Filesystem
  storageClassName: changedetection
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  mountOptions:
    - hard
    - nfsvers=4.1
  nfs:
    path: /home/devops/nfs_share/changedetection
    server: 172.20.0.22
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: changedetection-storage
spec:
  storageClassName: changedetection
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 5Gi