apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: changedetection-vs
spec:
  gateways:
  - istio-system/default-gateway
  hosts:
  - detector.proxmox.homelab
  http:
  - match:
    - uri:
        prefix: /
    route:
    - destination:
        host: detector-changedetection.default.svc.cluster.local
        port:
          number: 5000