apiVersion: apps/v1
kind: Deployment
metadata:
  name: application
spec:
  template:
    spec:
      containers:
      - name: application
        startupProbe:
          httpGet:
            path: /
            port: 8000
          periodSeconds: 10
          failureThreshold: 30
        readinessProbe:
          httpGet:
            path: /
            port: 8000
          periodSeconds: 10
          failureThreshold: 5