apiVersion: apps/v1
kind: Deployment
metadata:
  name: application
spec:
  template:
    spec:
      containers:
      - name: application
        envFrom:
        - secretRef:
            name: paperless-secret
        ports:
        - $patch: replace
        - containerPort: 8000