services:
  glance:
    container_name: glance
    image: glanceapp/glance:v0.8.2
    restart: unless-stopped
    volumes:
      - ./config:/app/config
      - ./assets:/app/assets
    ports:
      - 8080:8080
    env_file: .env
