apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../base
- vs.yaml
patches:
  - path: patches/add-config.yaml
namePrefix: glance-
images:
- name: ghcr.io/guyzsarun-lab/base
  newName: glanceapp/glance
  newTag: v0.8.2
commonLabels:
  app: glance
configMapGenerator:
- name: config
  files:
  - home.yml=config/home.yml
  - glance.yml=config/glance.yml
- name: assets
  files:
  - user.css=assets/user.css
