apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../base
- paperless-secret.yaml
- volume.yaml
- vs.yaml
namePrefix: paperless-
images:
- name: ghcr.io/guyzsarun-lab/base
  newName: ghcr.io/paperless-ngx/paperless-ngx
  newTag: 2.17.1
commonLabels:
  app: paperless
patches:
- path: patches/deployment-secret.yaml
- path: patches/deployment-memory.yaml
- path: patches/deployment-probe.yaml
- path: patches/service.yaml