name: Reusable Docker Build
on:
  workflow_call:
    inputs:
      path:
        required: true
        type: string

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out Git repository
        uses: actions/checkout@v4

      - name: Build Docker image
        uses: docker/build-push-action@v5
        with:
          context: ${{ inputs.path }}
          file: ${{ inputs.path}}/Dockerfile
          push: false
