apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../base
namePrefix: dashy-
images:
- name: ghcr.io/guyzsarun-lab/base
  newName: ghcr.io/guyzsarun-lab/dashy
  newTag: 0.0.1
commonLabels:
  app: dashy
patches:
- path: patches/add-config.yaml
- path: patches/set-memory.yaml
- path: patches/service.yaml
configMapGenerator:
- name: config
  files:
  - conf.yml=config.yml