apiVersion: apps/v1
kind: Deployment
metadata:
  name: application
spec:
  template:
    spec:
      containers:
      - name: application
        envFrom:
        - secretRef:
            name: linkwarden-secret
        volumeMounts:
        - name: linkwarden-data
          mountPath: /data/data
          subPath: linkwarden
        ports:
        - $patch: replace
        - containerPort: 3000
      - name: meilisearch
        image: getmeili/meilisearch:v1.15.2
        envFrom:
        - secretRef:
            name: linkwarden-secret
        volumeMounts:
        - name: linkwarden-data
          mountPath: /meili_data
          subPath: meilisearch
      volumes:
      - name: linkwarden-data
        persistentVolumeClaim:
          claimName: pvc