apiVersion: apps/v1
kind: Deployment
metadata:
  name: application
spec:
  template:
    spec:
      containers:
      - name: application
        resources:
          limits:
            memory: 1.5Gi
            cpu: 300m
      - name: meilisearch
        image: getmeili/meilisearch:v1.15.2
        resources:
          limits:
            memory: 1Gi
            cpu: 200m