apiVersion: v1
kind: PersistentVolume
metadata:
  name: <app-name>-pv
spec:
  capacity:
    storage: 10Gi
  volumeMode: Filesystem
  storageClassName: <app-name>-storage
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  mountOptions:
    - hard
    - nfsvers=4.1
  nfs:
    path: /home/devops/nfs_share/<app-name>
    server: nfs.proxmox.homelab
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: <app-name>-pvc
spec:
  storageClassName: <app-name>-storage
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 10Gi
