apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../base
- homepage-secret.yaml
namePrefix: homepage-
images:
- name: ghcr.io/guyzsarun-lab/base
  newName: ghcr.io/guyzsarun-lab/homepage
  newTag: 0.0.1
commonLabels:
  app: homepage
patches:
- path: patches/deployment.yaml
- path: patches/service.yaml