apiVersion: batch/v1
kind: Job
metadata:
  name: app-telegram-notification
  annotations:
    argocd.argoproj.io/hook: PostSync
    argocd.argoproj.io/hook-delete-policy: HookSucceeded
spec:
  template:
    spec:
      containers:
      - name: telegram-notification
        image: ghcr.io/guyzsarun-lab/apprise:0.0.1
        command: ["/bin/sh", "-c"]
        args:
          - >-
            apprise -vv
            -t "✅ Successfully deployed ${APP_NAME}"
            -b "Revision: ${APP_REVISION} | Namespace: ${APP_NAMESPACE}"
            "${TELEGRAM_URL}"
        env:
          - name: APP_NAME
            value: $ARGOCD_APP_NAME
          - name: APP_REVISION
            value: $ARGOCD_APP_REVISION
          - name: APP_NAMESPACE
            value: $ARGOCD_APP_NAMESPACE
          - name: TELEGRAM_URL
            valueFrom:
              secretKeyRef:
                name: apprise-channel
                key: telegram
      restartPolicy: Never
      imagePullSecrets:
      - name: image-pull-secret
  backoffLimit: 1
---
apiVersion: batch/v1
kind: Job
metadata:
  name: app-telegram-notification-fail
  annotations:
    argocd.argoproj.io/hook: SyncFail
    argocd.argoproj.io/hook-delete-policy: HookSucceeded
spec:
  template:
    spec:
      containers:
      - name: telegram-notification
        image: ghcr.io/guyzsarun-lab/apprise:0.0.1
        command: ["/bin/sh", "-c"]
        args:
          - >-
            apprise -vv
            -t "❌ Failed to deploy ${APP_NAME}"
            -b "Revision: ${APP_REVISION} | Namespace: ${APP_NAMESPACE}"
            "${TELEGRAM_URL}"
        env:
          - name: APP_NAME
            value: $ARGOCD_APP_NAME
          - name: APP_REVISION
            value: $ARGOCD_APP_REVISION
          - name: APP_NAMESPACE
            value: $ARGOCD_APP_NAMESPACE
          - name: TELEGRAM_URL
            valueFrom:
              secretKeyRef:
                name: apprise-channel
                key: telegram
      restartPolicy: Never
      imagePullSecrets:
      - name: image-pull-secret
  backoffLimit: 1