apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: secret
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault-backend
  dataFrom:
  - find:
    extract:
      key: "homelab/kubernetes/default/linkwarden"
      metadataPolicy: None
      conversionStrategy: Default
      decodingStrategy: None