apiVersion: apps/v1
kind: Deployment
metadata:
  name: application
spec:
  template:
    spec:
      volumes:
        - name: calibre-storage
          persistentVolumeClaim:
            claimName: calibre-calibre-pvc
      containers:
      - name: application
        volumeMounts:
        - mountPath: /config
          subPath: config
          name: calibre-storage
        - mountPath: /books
          name: calibre-storage
          subPath: books