apiVersion: apps/v1
kind: Deployment
metadata:
  name: application
spec:
  template:
    spec:
      containers:
      - name: application
        resources:
          limits:
            memory: 256Mi
            cpu: 100m
        ports:
        - $patch: replace
        - containerPort: 8083
        envFrom:
        - configMapRef:
            name: calibre-config
