apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../base
namePrefix: toolchain-
images:
- name: ghcr.io/guyzsarun-lab/base
  newName: ghcr.io/guyzsarun-lab/toolchain
  newTag: 0.0.2
commonLabels:
  app: toolchain