apiVersion: apps/v1
kind: Deployment
metadata:
  name: application
spec:
  template:
    spec:
      containers:
      - name: application
        resources:
          limits:
            memory: 128Mi
        envFrom:
        - secretRef:
            name: homepage-secret
        - configMapRef:
            name: homepage-config
        ports:
        - $patch: replace
        - containerPort: 3000