apiVersion: networking.istio.io/v1
kind: VirtualService
metadata:
  name: vs
spec:
  gateways:
    - istio-system/default-gateway
  hosts:
    - memos.proxmox.homelab
  http:
    - route:
        - destination:
            host: memos-application
            port:
              number: 5230
