apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../base
namePrefix: cyberchef-
images:
- name: ghcr.io/guyzsarun/base
  newName: ghcr.io/guyzsarun/utils
  newTag: v10.18.6
commonLabels:
  app: cyberchef