apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../base
- volume.yaml
- vs.yaml
namePrefix: calibre-
images:
- name: ghcr.io/guyzsarun-lab/base
  newName: linuxserver/calibre-web
  newTag: 0.6.24
commonLabels:
  app: calibre
patches:
- path: patches/deployment-config.yaml
- path: patches/deployment-volume.yaml
- path: patches/service.yaml


configMapGenerator:
- name: calibre-config
  literals:
  - PUID=1000
  - PGID=1000
  - TZ=Etc/UTC
  - DOCKER_MODS=linuxserver/mods:universal-calibre #optional
  - OAUTHLIB_RELAX_TOKEN_SCOPE=1 #optional
