apiVersion: v1
kind: PersistentVolume
metadata:
  name: calibre-pv
spec:
  capacity:
    storage: 10Gi
  volumeMode: Filesystem
  storageClassName: calibre
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  mountOptions:
    - hard
    - nfsvers=4.1
  nfs:
    path: /home/devops/nfs_share/calibre
    server: 172.20.0.22
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: calibre-pvc
spec:
  storageClassName: calibre
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 10Gi