apiVersion: networking.istio.io/v1
kind: VirtualService
metadata:
  name: vs
spec:
  gateways:
  - istio-system/default-gateway
  hosts:
  - calibre.proxmox.homelab
  - calibre.guyzsarun.xyz
  http:
  - route:
    - destination:
        host: calibre-application
        port:
          number: 3000