nextcloud:
  nextcloud:
    host: nextcloud.proxmox.local
    existingSecret:
      enabled: true
      secretName: nextcloud-secret
      usernameKey: nextcloud-username
      passwordKey: nextcloud-password
    trustedDomains: ['localhost','nextcloud.proxmox.local','nextcloud.guyzsarun.xyz']
  livenessProbe:
    enabled: false
  readinessProbe:
    enabled: false

  internalDatabase:
    enabled: true
    name: nextcloud

  persistence:
    enabled: true
    existingClaim: nextcloud-pvc
    accessMode: ReadWriteOnce
    size: 10Gi
