nextcloud:
  nextcloud:
    host: nextcloud.proxmox.local
    username: admin
    password: P@ssw0rd
    update: 0
    # If web server is not binding default port, you can define it
    containerPort: 80
    datadir: /var/www/html/data
    persistence:
      subPath:
    defaultConfigs:
      # To protect /var/www/html/config
      .htaccess: true
      # Redis default configuration
      redis.config.php: true
      # Apache configuration for rewrite urls
      apache-pretty-urls.config.php: true
      # Define APCu as local cache
      apcu.config.php: true
      # Apps directory configs
      apps.config.php: true
      # Used for auto configure database
      autoconfig.php: true
      # SMTP default configuration
      smtp.config.php: true
    # Extra config files created in /var/www/html/config/
    # ref: https://docs.nextcloud.com/server/15/admin_manual/configuration_server/config_sample_php_parameters.html#multiple-config-php-file
    configs:
      trusted_domains.config.php: |-
        <?php
        $CONFIG = [
          'trusted_domains' => [
            0 => 'localhost',
            1 => 'nextcloud.kube.home',
            2 => 'nextcloud.promxox.local',
          ]
        ];
  livenessProbe:
    enabled: false

    # For example, to use S3 as primary storage
    # ref: https://docs.nextcloud.com/server/13/admin_manual/configuration_files/primary_storage.html#simple-storage-service-s3
    #
    #  configs:
    #    s3.config.php: |-
    #      <?php
    #      $CONFIG = array (
    #        'objectstore' => array(
    #          'class' => '\\OC\\Files\\ObjectStore\\S3',
    #          'arguments' => array(
    #            'bucket'     => 'my-bucket',
    #            'autocreate' => true,
    #            'key'        => 'xxx',
    #            'secret'     => 'xxx',
    #            'region'     => 'us-east-1',
    #            'use_ssl'    => true
    #          )
    #        )
    #      );

  internalDatabase:
    enabled: true
    name: nextcloud

  persistence:
    enabled: true
    existingClaim: nextcloud-pvc
    accessMode: ReadWriteOnce
    size: 10Gi
