name: release

on:
  push:
    tags:
      - '*'
  workflow_dispatch:

jobs:
  get-version:
    outputs:
      version: ${{ steps.extract_version.outputs.version }}
      application_name: ${{ steps.extract_version.outputs.application_name }}
    runs-on: ubuntu-latest
    steps:
      - name: parse application name and version
        id: extract_version
        run: |
          TAG=${GITHUB_REF_NAME}

          APP_NAME=${TAG%-*}
          VERSION=${TAG##*-}
          echo "application_name=$APP_NAME" >> $GITHUB_ENV
          echo "version=$VERSION" >> $GITHUB_ENV

  docker-build:
    needs: get-version
    uses: ./.github/workflows/reusable-docker-build.yaml
    with:
      path: applicationset/${{ needs.get-version.outputs.application_name }}
      version: ${{ needs.get-version.outputs.version }}


  # update-version:
  #   if: github.event.inputs.release == 'true'
  #   runs-on: ubuntu-latest
  #   permissions:
  #     contents: write
  #   needs: build-image
  #   steps:
  #   - name: Check out Git repository
  #     uses: actions/checkout@v4

  #   - name: Update Version
  #     run: |
  #       sed -i "s/\(newTag:\s*\).*/\1${{ github.event.inputs.version }}/" ${{ github.event.inputs.project }}/kustomization.yaml
  #       cat ${{ github.event.inputs.project }}/kustomization.yaml


  #   - name: Commit files
  #     run: |
  #       git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
  #       git config --local user.name "github-actions[bot]"
  #       cat ${{ github.event.inputs.project }}/kustomization.yaml
  #       git add .
  #       git commit -m "Update ${{ github.event.inputs.project }} to version ${{ github.event.inputs.version }}"

  #   - name: Push changes
  #     uses: ad-m/github-push-action@master
  #     with:
  #       github_token: ${{ secrets.GITHUB_TOKEN }}
  #       branch: ${{ github.ref }}
