name: Reusable Docker Build
on:
  workflow_call:
    inputs:
      path:
        required: true
        type: string
      push:
        required: false
        type: boolean
        default: false
      version:
        required: false
        type: string
        default: 'latest'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out Git repository
        uses: actions/checkout@v4

      - name: Log in to GitHub Container Registry
        if: ${{ inputs.push }}
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GH_TOKEN }}

      - name: Build Docker image
        uses: docker/build-push-action@v5
        with:
          build-args: |
            VERSION=${{ inputs.version }}
          context: ${{ inputs.path }}
          file: ${{ inputs.path}}/Dockerfile
          push: ${{ inputs.push }}
          tags: "ghcr.io/guyzsarun-lab/${{ inputs.path }}:${{ inputs.version }}"
          labels: "org.opencontainers.image.source=https://github.com/guyzsarun-lab/gitops"
